
insert into songs (Title, Artist, Genre) values ('Majestic Mountain Minuet', 'Alice Smith', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Ruby Red Reverie', 'Benjamin Ramirez', 'Metal');
insert into songs (Title, Artist, Genre) values ('Vibrant Valley Valse', 'Sophia Anderson', 'R&B');
insert into songs (Title, Artist, Genre) values ('Tranquil Tide Tarantella', 'Grace Murphy', 'Pop');
insert into songs (Title, Artist, Genre) values ('Frosty Forest Fugue', 'Benjamin Ramirez', 'Electronic');
insert into songs (Title, Artist, Genre) values ('Zephyr Zest Zamba', 'Alexander Perez', 'Metal');
insert into songs (Title, Artist, Genre) values ('Bamboo Breeze Ballad', 'Sophia Anderson', 'Classical');
insert into songs (Title, Artist, Genre) values ('Gossamer Glade Groove', 'John Johnson', 'Soul');
insert into songs (Title, Artist, Genre) values ('Bamboo Breeze Ballad', 'James Wilson', 'Metal');
insert into songs (Title, Artist, Genre) values ('Velvet Violet Visions', 'Amelia Torres', 'Rock');
insert into songs (Title, Artist, Genre) values ('Whispering Willow Waltz', 'John Johnson', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Whimsical Waterfall Warble', 'Daniel Martinez', 'Electronic');
insert into songs (Title, Artist, Genre) values ('Sapphire Shores Scherzo', 'James Wilson', 'Pop');
insert into songs (Title, Artist, Genre) values ('Whispers in the Wind', 'Olivia Taylor', 'Soul');
insert into songs (Title, Artist, Genre) values ('Topaz Twilight Tune', 'William Thomas', 'Rock');
insert into songs (Title, Artist, Genre) values ('Ruby Red Reverie', 'Sarah White', 'R&B');
insert into songs (Title, Artist, Genre) values ('Vibrant Valley Valse', 'Sophia Anderson', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Glimmering Grotto Gigue', 'Harper Adams', 'Reggae');
insert into songs (Title, Artist, Genre) values ('Utopian Ukelele Undulation', 'David Lee', 'Classical');
insert into songs (Title, Artist, Genre) values ('Astral Aura Anthem', 'Ella Hughes', 'Blues');
insert into songs (Title, Artist, Genre) values ('Serenading Sunbeam Sonata', 'Sarah White', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Coral Cove Cantata', 'Jacob Flores', 'Pop');
insert into songs (Title, Artist, Genre) values ('Dewdrop Duet Dirge', 'Benjamin Ramirez', 'Blues');
insert into songs (Title, Artist, Genre) values ('Glimmering Grotto Gigue', 'Daniel Martinez', 'Metal');
insert into songs (Title, Artist, Genre) values ('Utopian Ukelele Undulation', 'Andrew Coleman', 'Folk');
insert into songs (Title, Artist, Genre) values ('Cerulean Cascade Cadenza', 'Amelia Torres', 'Classical');
insert into songs (Title, Artist, Genre) values ('Enchanted Melody', 'Andrew Coleman', 'Classical');
insert into songs (Title, Artist, Genre) values ('Violet Velvet Visions', 'Ethan Hernandez', 'R&B');
insert into songs (Title, Artist, Genre) values ('Silver Moonlight Sonata', 'Benjamin Ramirez', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Blossom Breeze Bolero', 'Jacob Flores', 'Classical');
insert into songs (Title, Artist, Genre) values ('Oceanic Rhapsody', 'John Johnson', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Radiant Rainbow Rondo', 'Andrew Coleman', 'Soul');
insert into songs (Title, Artist, Genre) values ('Quartz Quarry Quadrille', 'John Johnson', 'Folk');
insert into songs (Title, Artist, Genre) values ('Tranquil Tide Tarantella', 'Isabella Rodriguez', 'Pop');
insert into songs (Title, Artist, Genre) values ('Whispers in the Wind', 'Grace Murphy', 'R&B');
insert into songs (Title, Artist, Genre) values ('Serenading Sunbeam Sonata', 'Sophia Anderson', 'Soul');
insert into songs (Title, Artist, Genre) values ('Kaleidoscope Keys Kyrie', 'Matthew Russell', 'Soul');
insert into songs (Title, Artist, Genre) values ('Icicle Interlude Impromptu', 'Mia Lopez', 'Classical');
insert into songs (Title, Artist, Genre) values ('Utopian Ukelele Undulation', 'Harper Adams', 'Pop');
insert into songs (Title, Artist, Genre) values ('Jubilant Jungle Jive', 'Alexander Perez', 'Metal');
insert into songs (Title, Artist, Genre) values ('Silver Moonlight Sonata', 'David Lee', 'Indie');
insert into songs (Title, Artist, Genre) values ('Lagoon Lullaby Lament', 'Alice Smith', 'Pop');
insert into songs (Title, Artist, Genre) values ('Utopian Ukelele Undulation', 'Alexander Perez', 'Soul');
insert into songs (Title, Artist, Genre) values ('Twilight Lullaby', 'Sophia Anderson', 'Punk');
insert into songs (Title, Artist, Genre) values ('Serenading Sunbeam Sonata', 'Isabella Rodriguez', 'Punk');
insert into songs (Title, Artist, Genre) values ('Kaleidoscope Keys Kyrie', 'Mia Lopez', 'Electronic');
insert into songs (Title, Artist, Genre) values ('Vibrant Valley Valse', 'Michael Brown', 'Electronic');
insert into songs (Title, Artist, Genre) values ('Radiant Rainbow Rhapsody', 'Benjamin Ramirez', 'Rock');
insert into songs (Title, Artist, Genre) values ('Turquoise Twilight Tango', 'Sophia Anderson', 'Metal');
insert into songs (Title, Artist, Genre) values ('Pristine Peak Polonaise', 'David Lee', 'Indie');
insert into songs (Title, Artist, Genre) values ('Majestic Mountain Minuet', 'James Wilson', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Utopian Ukelele Undulation', 'William Thomas', 'Blues');
insert into songs (Title, Artist, Genre) values ('Utopian Ukelele Unison', 'Benjamin Ramirez', 'Indie');
insert into songs (Title, Artist, Genre) values ('Frostbite Fandango Fantasia', 'Alice Smith', 'R&B');
insert into songs (Title, Artist, Genre) values ('Emerald Echoes', 'Jacob Flores', 'Blues');
insert into songs (Title, Artist, Genre) values ('Kaleidoscope Keys Kyrie', 'Amelia Torres', 'R&B');
insert into songs (Title, Artist, Genre) values ('Pristine Peak Polonaise', 'Harper Adams', 'Classical');
insert into songs (Title, Artist, Genre) values ('Utopian Ukelele Unison', 'John Johnson', 'Pop');
insert into songs (Title, Artist, Genre) values ('Silver Moonlight Sonata', 'Andrew Coleman', 'Soul');
insert into songs (Title, Artist, Genre) values ('Vibrant Valley Valse', 'Isabella Rodriguez', 'Folk');
insert into songs (Title, Artist, Genre) values ('Whimsical Waterfall Warble', 'Ella Hughes', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Luminous Lagoon Lullaby', 'David Lee', 'Reggae');
insert into songs (Title, Artist, Genre) values ('Vibrant Valley Virelai', 'Sophia Anderson', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Sapphire Shores Scherzo', 'Jacob Flores', 'Classical');
insert into songs (Title, Artist, Genre) values ('Oasis Overture Ode', 'Ethan Hernandez', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Utopian Ukelele Unison', 'Ella Hughes', 'Electronic');
insert into songs (Title, Artist, Genre) values ('Crimson Sunset Serenade', 'James Wilson', 'Punk');
insert into songs (Title, Artist, Genre) values ('Aurora Borealis Blues', 'Sarah White', 'Classical');
insert into songs (Title, Artist, Genre) values ('Moonlit Sonata', 'Andrew Coleman', 'Blues');
insert into songs (Title, Artist, Genre) values ('Gossamer Glade Groove', 'Charlotte Gonzalez', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Midnight Serenade', 'Andrew Coleman', 'Pop');
insert into songs (Title, Artist, Genre) values ('Dandelion Dreams Duet', 'Ella Hughes', 'Folk');
insert into songs (Title, Artist, Genre) values ('Aurora Borealis Blues', 'Sarah White', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Whimsical Waterfall Warble', 'Benjamin Ramirez', 'Metal');
insert into songs (Title, Artist, Genre) values ('Sapphire Shores Symphony', 'Jacob Flores', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Coral Cove Cantata', 'Mia Lopez', 'Country');
insert into songs (Title, Artist, Genre) values ('Violet Velvet Visions', 'Charlotte Gonzalez', 'Soul');
insert into songs (Title, Artist, Genre) values ('Sunset Symphony', 'Emily Davis', 'Classical');
insert into songs (Title, Artist, Genre) values ('Kaleidoscope Keys Kyrie', 'Alexander Perez', 'Electronic');
insert into songs (Title, Artist, Genre) values ('Frosty Forest Fugue', 'Matthew Russell', 'Pop');
insert into songs (Title, Artist, Genre) values ('Starry Night Waltz', 'Charlotte Gonzalez', 'Indie');
insert into songs (Title, Artist, Genre) values ('Frostbite Fandango Fantasia', 'Andrew Coleman', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Radiant Rainbow Rhapsody', 'Ella Hughes', 'Country');
insert into songs (Title, Artist, Genre) values ('Crimson Sunset Serenade', 'Jacob Flores', 'Reggae');
insert into songs (Title, Artist, Genre) values ('Harmonic Horizon Hymn', 'Matthew Russell', 'Blues');
insert into songs (Title, Artist, Genre) values ('Quartz Quarry Quartet', 'Harper Adams', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Coral Cove Cantata', 'John Johnson', 'Indie');
insert into songs (Title, Artist, Genre) values ('Astral Aura Anthem', 'Grace Murphy', 'Country');
insert into songs (Title, Artist, Genre) values ('Tranquil Tide Tarantella', 'Sophia Anderson', 'Folk');
insert into songs (Title, Artist, Genre) values ('Azure Skies Serenade', 'Alexander Perez', 'Classical');
insert into songs (Title, Artist, Genre) values ('Utopian Ukelele Unison', 'Sarah White', 'Electronic');
insert into songs (Title, Artist, Genre) values ('Tranquil Tide Tarantella', 'Charlotte Gonzalez', 'Indie');
insert into songs (Title, Artist, Genre) values ('Astral Aura Anthem', 'Olivia Taylor', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Kaleidoscope Klavier Kyrie', 'Harper Adams', 'Indie');
insert into songs (Title, Artist, Genre) values ('Zenith Zephyr Zither Zither', 'Alice Smith', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Ruby Red Reverie', 'Emily Davis', 'Classical');
insert into songs (Title, Artist, Genre) values ('Rose Quartz Rhapsody', 'David Lee', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Lagoon Lullaby Lament', 'Amelia Torres', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Tranquil Tide Tarantella', 'Alice Smith', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Silver Moonlight Sonata', 'Jacob Flores', 'Indie');
