from connect import *
from readFilms import all_films

dbCursor.execute("UPDATE tblFilms SET Title = 'Fight Club', Rating = '4 stars - Solid acting, amazing direction - watch!' WHERE filmID = 1")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Shining', Rating = '5 stars - Unforgettable turn from Jack Nicholson.' WHERE filmID = 2")
dbCursor.execute("UPDATE tblFilms SET Genre = 'Mystery/Thriller/Drama' WHERE filmID = 2")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Breakfast Club', Rating = '5 stars - Very funny - must watch!' WHERE filmID = 3")
dbCursor.execute("UPDATE tblFilms SET Title = 'Singin* in the Rain', Rating = '5+ stars - A masterpiece - must watch!' WHERE filmID = 4")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Matrix', Rating = '5 stars - Spectacular action and special effects.' WHERE filmID = 5")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Great Gatsby', Rating = '2 stars - Talented leads not enough.' WHERE filmID = 6")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Lion King', Rating = '5+ stars - Emotionally stirring, richly drawn.' WHERE filmID = 7")
dbCursor.execute("UPDATE tblFilms SET Genre = 'Animated/Kids/Musical' WHERE filmID = 7")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Matrix Reloaded', Rating = '4 stars - A worthy sequel to watch.' WHERE filmID = 8")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Sound of Music', Rating = '5 stars - Unapologetically sweet and corny.' WHERE filmID = 9")
dbCursor.execute("UPDATE tblFilms SET Title = 'Black Panther', Rating = '5+ stars - Raises superhero cinema to new heights.' WHERE filmID = 10")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Exorcist', Rating = '4 stars - Eerie with remarkable special effects' WHERE filmID = 11")
dbCursor.execute("UPDATE tblFilms SET Title = 'Midnight in Paris', Rating = '5 stars - Sweetly sentimental, funny, charming.' WHERE filmID = 12")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Wizard of Oz', Rating = '5+ stars - An absolute masterpiece.' WHERE filmID = 13")
dbCursor.execute("UPDATE tblFilms SET Title = 'Once Upon a Time in America', Rating = '5 stars - A solid film with great performances.' WHERE filmID = 14")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Shawshank Redemption', Rating = '5 stars - Uplifting, deeply satisfying drama.' WHERE filmID = 15")
dbCursor.execute("UPDATE tblFilms SET Title = 'Black Death', Rating = '4 stars - worth a watch.' WHERE filmID = 16")
dbCursor.execute("UPDATE tblFilms SET Genre = 'Thriller/Horror' WHERE filmID = 16")
dbCursor.execute("UPDATE tblFilms SET Title = 'Pulp Fiction', Rating = '5 stars - This movie is amazing.' WHERE filmID = 17")
dbCursor.execute("UPDATE tblFilms SET Title = 'Snake Charmer', Rating = 'Critically unrated but zero from me.' WHERE filmID = 18")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Sound of Summer', Rating = 'Critically unrated and not viewed by myself.' WHERE filmID = 19")
dbCursor.execute("UPDATE tblFilms SET Title = 'Jaws', Rating = '5+ stars - A solid film with great performances.' WHERE filmID = 20")
dbCursor.execute("UPDATE tblFilms SET Genre = 'Thriller/Horror' WHERE filmID = 20")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Madness of King George', Rating = '5 stars - Stellar performances and caste.' WHERE filmID = 21")
dbCursor.execute("UPDATE tblFilms SET Title = 'Sunshine', Rating = '4 stars - Very reasonable.' WHERE filmID = 22")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Green Mile', Rating = '4 stars - Long - an absorbing, powerful experience' WHERE filmID = 23")
dbCursor.execute("UPDATE tblFilms SET Title = 'Metropolis', Rating = '5+ stars - Visually inspiring old sci-fi classic.' WHERE filmID = 24")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Idle Class', Rating = '5+ stars - Top draw Charlie Chaplin slapstick.' WHERE filmID = 25")
dbCursor.execute("UPDATE tblFilms SET Title = 'Titanic', Rating = '5 stars - A triumph for James Cameron.' WHERE filmID = 26")
dbCursor.execute("UPDATE tblFilms SET Title = 'Back to the Future', Rating = '5 stars - Inventive, funny, breathlessly built.' WHERE filmID = 27")
dbCursor.execute("UPDATE tblFilms SET Title = 'Severn Samurai (Japanese)', Rating = '5+ stars - Akira Kurosawa*s epic masterpiece.' WHERE filmID = 28")
dbCursor.execute("UPDATE tblFilms SET Title = 'A Fistful of Dollar', Rating = '5+ stars - Leone*s take on Kurosawa*s Yojimbo.' WHERE filmID = 29")
dbCursor.execute("UPDATE tblFilms SET Title = 'Gone with the Wind', Rating = '5 stars - Epic grandeur and romantic allure.' WHERE filmID = 30")
dbCursor.execute("UPDATE tblFilms SET Title = 'Once Upon a Texas Train', Rating = '1 star - Rated by 1 & myself - don*t watch.' WHERE filmID = 31")
dbCursor.execute("UPDATE tblFilms SET Title = 'Taxi (French: Gérard Pirès)', Rating = '4 stars - Critically unrated but worth a watch.' WHERE filmID = 32")
dbCursor.execute("UPDATE tblFilms SET Title = 'Transsiberian [sic]', Rating = '5 stars - Effective in execution, a taut thriller.' WHERE filmID = 33")
dbCursor.execute("UPDATE tblFilms SET Genre = 'Mystery/Thriller/Crime' WHERE filmID = 33")
dbCursor.execute("UPDATE tblFilms SET Title = 'Twilight Zone: The Movie', Rating = '3 stars - Suffers from typical anthology vagaries.' WHERE filmID = 34")
dbCursor.execute("UPDATE tblFilms SET Title = '2001: A Space Odyssey', Rating = '5 stars - A most influential sci-fi film - watch!' WHERE filmID = 35")
dbCursor.execute("UPDATE tblFilms SET Title = 'The Fountain', Rating = '3 stars - Metaphysics, patterns, Biblical symbols.' WHERE filmID = 36")
dbCursor.execute("UPDATE tblFilms SET Genre = 'Mystery/Fantasy/Drama' WHERE filmID = 36")
dbCursor.execute("UPDATE tblFilms SET Title = 'Monty Python & the Holy Grail', Rating = '5+ stars - Cult classic, gut-bustingly hilarious.' WHERE filmID = 37")
    
dbCon.commit()

# now call the all_films function from the readFilms file to display updated records
all_films()

